### ISSUE TITLE
pre-processing failed for  aligned_reads.sorted.bam

### ISSUE THREAD

**Issue by xibeixingchen** [Gabaldonlab/perSVade#10]
Hi,

When I used code `singularity exec -e /home/jiazc/software/persvade_v1.sif bash -c 'source /opt/conda/etc/profile.d/conda.sh && conda activate perSVade_env && python /perSVade/scripts/perSVade call_SVs --ref /home/jiazc/work/alfalfa_genome/Muxu_Genome_Final_filter.fasta -o /home/jiazc/work/persvade_output/call_SVs -sbam /home/jiazc/work/sort_bam/B1.sort.markdup.bam --mitochondrial_chromosome no_mitochondria --SVcalling_parameters /home/jiazc/work/persvade_output/parameter_optimization/optimized_parameters.json --repeats_file /home/jiazc/work/persvade_output/repeat_inference/combined_repeats.new.tab --verbose --fraction_available_mem 0.1 --threads 16 --fractionRAM_to_dedicate 0.7'` ,
and there is a error, and it is list in following.
[b1.snv.log](https://github.com/Gabaldonlab/perSVade/files/9948955/b1.snv.log)

[gridss_run_std.txt](https://github.com/Gabaldonlab/perSVade/files/9948956/gridss_run_std.txt)

my sorted.bam happend problmes? But bam files don't map by perSVade, by bwa-samtools maping.

Thanks,
Best.
Zhicheng Jia

**Comment by MikiSchikora** [comment]
Hi,

I see that there is some formating problem with your bam file, since gridss failed at the preprocessing step. As far as I understand, your bam files were not generated by perSVade align_reads, which could be the source of the problem. Gridss has some strict requirements of how the bam has to be, and some bam files may not work. Could you run call_SVs using perSVade's aligned reads? Note that the align_reads module will output a file 'all_cmds.txt' where you can see the exact commands that perSVade used to align the reads.

If you want to use your bam, you may check the full log of gridss from `/home/jiazc/work/persvade_output/call_SVs/SVdetection_output/final_gridss_running/gridss_tmp/gridss.full.20221107_144232.forageseed.64531.log`, and ask the developers of gridss [here](https://github.com/PapenfussLab/gridss) for help, since this is a gridss problem.

Kind regards,
Miquel Àngel Schikora

**Comment by xibeixingchen** [comment]
Hi, 

Thanks your reply, When I used perSVade align_reads module, and then run call_SVs, a same arror is emering.
align_reads code like `singularity exec -e /home/jiazc/software/persvade_v1.sif bash -c 'source /opt/conda/etc/profile.d/conda.sh && conda activate perSVade_env && python /perSVade/scripts/perSVade align_reads -f1 /home/jiazc/work/rawdata/B1.R1.fq.gz -f2 /home/jiazc/work/rawdata/B1.R2.fq.gz --ref /home/jiazc/work/alfalfa_genome/Muxu_Genome_Final_filter.fasta --fraction_available_mem 0.3 -o /home/jiazc/work/persvade_output/B1/aligned_reads --verbose --fraction_available_mem 0.3 --threads 32'`
sv_call code like `singularity exec -e /home/jiazc/software/persvade_v1.sif bash -c 'source /opt/conda/etc/profile.d/conda.sh && conda activate perSVade_env && python /perSVade/scripts/perSVade call_SVs --ref /home/jiazc/work/alfalfa_genome/Muxu_Genome_Final_filter.fasta -o /home/jiazc/work/persvade_output/B1/call_SVs -sbam /home/jiazc/work/persvade_output/B1/aligned_reads/aligned_reads.bam.sorted --mitochondrial_chromosome no_mitochondria --SVcalling_parameters /home/jiazc/work/persvade_output/parameter_optimization_random/optimized_parameters.json --repeats_file skip --verbose --fraction_available_mem 0.3'`
[gridss.full.20221108_174048.forageseed.4867.log](https://github.com/Gabaldonlab/perSVade/files/9959832/gridss.full.20221108_174048.forageseed.4867.log)

Thanks,
Best,
Zhicheng Jia

**Comment by MikiSchikora** [comment]
Hi,

Is this something specific to this sample? Could you run sucessfully call_SVs on other samples with the same commands and reference genomes? Maybe this helps me figure out what happened.

I see this 'Exception in thread "main" java.lang.IllegalArgumentException: Reference name for '182' not found in sequence dictionary.' line in the full log, which seems to be triggering the error. Is it possible that the bam file has chromosomes (such as '182') that are not in the reference genome?

Kind regards,
Miquel Àngel Schikora

**Comment by MikiSchikora** [comment]
Hi,

Could you solve this?

Kind regards,
Miquel Àngel Schikora
