### ISSUE TITLE
How can do joint calling for multiple samples

### ISSUE THREAD

**Issue by DrChunLi** [Gabaldonlab/perSVade#13]
Dear Sir:
gridss suggest that "Joint calling should always be used for related samples", but I can NOT find any instruction for joint calling in the perSVade guide.
How should I do to run joint calling?

**Comment by MikiSchikora** [comment]
Good morning,

We have currently not implemented a joint calling strategy, since perSVade is focused on providing variant calls for single samples. I am working on a module to compare the SVs found in different samples and keep sample-specific variants, which is conceptually similar to joint calling. 

Imagine that you set of sample A  (i.e. a tumor) variants and you want to remove the variants that are in another sample B (a matched normal sample). I'd use bedmap to define the variants from sample A that do not overlap any breakpoint from sample B. I'd use the unfiltered gridss results from sample B (provided in the perSVade output) to make sure that you remove all background variants. 

I am working on this pipeline, but I can't guarantee when it is going to be tested and ready. Maybe you can implement such a pipeline that suits your samples?

Best,
Miquel Àngel Schikora

**Comment by MikiSchikora** [comment]
Hi,
Is this solved? I'd close the issue if so.

Miquel Àngel Schikora
Barcelona Supercomputing Center

**Comment by DrChunLi** [comment]
Dear Sir:
Thank you for your reply, the issue can be closed, I got the answer. 
Best wishes.










At 2023-02-02 19:10:22, "MikiSchikora" ***@***.***> wrote:

Hi,
Is this solved? I'd close the issue if so.

Miquel Àngel Schikora
Barcelona Supercomputing Center
