### ISSUE TITLE
How to combiend different sample sv.vcf to a vcf

### ISSUE THREAD

**Issue by xibeixingchen** [Gabaldonlab/perSVade#17]
Hi,

I used persvade to generate vcf files for each sample, how do I merge the vcf of these samples into one total vcf? What about software like bctools

Thanks

**Comment by MikiSchikora** [comment]
Good morning,

This is currently a work in progress. Bcftools may be useful for vcfs that have SNPs and INDELs, so you can use it to create the merged vcf for small variants.

For SVs it is trickier, and it requires a bit of post-processing, as I don't think that bcftools will be able to handle all of the SV types. The goal is to integrate the CNVs and SVs from different samples in a way that equivalent variants get the same variant ID. This is not a trivial task, since the used algorithms often lack single-bp resolution, so that the same variant in different samples may get slightly different coordinates. To solve this, you may use bedmap (from the bedops suite) to cluster variants from the same SV type type that reciprocally overlap by >75% of their total length and where their breakpoints are <50bp from each other. Each cluster would be one variant.

I am working on this pipeline, but I can't guarantee when it is going to be tested and ready. Maybe you can implement such a pipeline that suits your samples?

Best,
Miquel Àngel Schikora

**Comment by xibeixingchen** [comment]
Hi,
Thanks for your professional answer, I found SURVIVOR software is specifically for sv, where `SURVIVOR merge` seems to be able to be used to merge multiple books into one sample, what do you suggest?

Best,
Zhicheng Jia

**Comment by MikiSchikora** [comment]
Hi,

This tool is interesting, you may try it and see how it works. However, I'd avise checking that the SVs handled by this tool will work with perSVade's SV types, as every tool has its own  definition of SV types. Note that, beyond the custom integrated vcf files, you can also work with (maybe more standard) gridss and clove outputs (gridss_output.filt.vcf, gridss_output.filt.bedpe, clove_output.vcf). Check [this](https://github.com/Gabaldonlab/perSVade/wiki/7.-Output#call_svs) to find out more. 

Note that this has some limitations. The gridss outputs only refer to the breakpoints. The clove output may have inaccuracies in the calling of tandem duplications and deletions, as it only relies on a single coverage filter for both. Still, since these are more standard tools, and depending on what you want to do, working with these outputs may be useful for you.

Best,
Miquel Àngel Schikora

**Comment by MikiSchikora** [comment]
Good morning,

Is this solved? I'd close the issue if so.

Best,
Miquel Àngel Schikora
