### ISSUE TITLE
mamba required for installation of dependencies

### ISSUE THREAD

**Issue by SAMtoBAM** [Gabaldonlab/perSVade#2]
Hi there, 

I am installing perSVade through the generic system using conda (mamba not installed), however during the dependency installation step I get this error:
`./installation/setup_environment.sh: line 74: mamba: command not found`
Meaning that it seems mamba has been made a requirement? can conda be used in the absence of mamba during the installation of these dependencies?

thanks

**Comment by MikiSchikora** [comment]
Good evening,

Right now mamba is required, yes. [mamba](https://mamba.readthedocs.io/en/latest/user_guide/mamba.html) works just like conda, but way faster. I could write a version of `./installation/setup_environment.sh` that works with conda instead of mamba, but it would take very long to create all the environments and I don't think that it'd be practical.

The [wiki](https://github.com/Gabaldonlab/perSVade/wiki/2.-Installation) shows how mamba should be installed in the `base` conda environment as a first step. I will clarify that this is necessary.

Would this be a good solution for futher users? Is there any reason by which you would not like to use mamba?

Hope this helps,

Miquel Àngel Schikora 
Barcelona Supercomputing Center

**Comment by MikiSchikora** [comment]
Hi again, 

I think that this is already cleared. If you fave further questions, just re-open this comment.

Thanks,

Miquel Àngel Schikora
Barcelona Supercomputing Center
